CREATE TABLE artwork (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image varbinary(max) NOT NULL,
    title TEXT NOT NULL,
    artist_name TEXT DEFAULT 'Unknown',
    price MONEY DEFAULT 'Unknown',
    description TEXT NOT NULL
);